import { COMPANY_WORKSPACE_ABI } from './abi';

export const COMPANY_WORKSPACE_ADDRESS = '0x70D66CDE91B8Cd131E7C57e9cd89D902b52F7e4D';

export const COMPANY_WORKSPACE_CONTRACT = {
  address: COMPANY_WORKSPACE_ADDRESS as `0x${string}`,
  abi: COMPANY_WORKSPACE_ABI,
};
